server:
  port: 8282
   datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/departmentServices
    username: root
    password: Akash3011@

# hibernate Configuration
  spring:
    jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
eurka:
  client:
   serviceUrl:
    deafaultZone: http://localhost:8761/eureka/
    #here we give our eurka server path where we want register our service.
management:
  tracing:
   sampling:
    probability: 1.0
